app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from familytool import views


tasks_api_router = DefaultRouter()
tasks_api_router.register(r"api/tasks", views.TaskViewSet, basename="api-task")

urlpatterns = [
    path("growth/", include("growth.urls")),
    path("robots.txt", views.robots, name="robots-txt"),

    re_path(r"^$", views.index, name="index"),
    re_path(r"^red/$", views.red, name="red"),

    re_path(r"^recipes/$", views.RecipeList.as_view(), name="recipe-list"),
    re_path(r"^create/$", views.RecipeCreate.as_view(), name="recipe-create"),
    re_path(r"^edit/(?P<pk>\d*)/$", views.RecipeUpdate.as_view(), name="recipe-edit"),
    re_path(r"^delete/(?P<pk>\d*)/$", views.RecipeDelete.as_view(), name="recipe-delete"),
    re_path(r"^tag/new/$", views.TagCreate.as_view()),
    re_path(r"^tag/edit/(?P<pk>\d*)/$", views.TagUpdate.as_view()),
    re_path(r"^tag/(?P<slug>[^/]+)/$", views.RecipeList.as_view()),
    re_path(r"^tag/delete/(?P<pk>\d*)/$", views.TagDelete.as_view()),
    re_path(r"^unit/new/$", views.UnitCreate.as_view()),
    re_path(r"^unit/delete/(?P<pk>\d*)/$", views.UnitDelete.as_view()),

    re_path(r"^item/new/$", views.ItemCreate.as_view(), name="item-create"),
    re_path(r"^item/bought/(?P<pk>\d*)/$", views.item_bought),
    re_path(r"^items/(?P<bought>bought)/$", views.ItemList.as_view(), name="bought-list"),
    re_path(r"^item/(?P<pk>\d*)/priority_increase/$", views.item_priority_increase, name="item-priority-increase"),
    re_path(r"^item/edit/(?P<pk>\d*)/$", views.ItemUpdate.as_view(), name="item-edit"),
    re_path(r"^item/delete/(?P<pk>\d*)/$", views.ItemDelete.as_view(), name="item-delete"),
    re_path(r"^items/$", views.ItemList.as_view(), name="item-list"),

    re_path(r"^expenses/$", views.ExpenseList.as_view(), name="expense-list"),
    re_path(r"^expense/edit/(?P<pk>\d*)/$", views.ExpenseUpdate.as_view(), name="expense-edit"),
    re_path(r"^expense/delete/(?P<pk>\d*)/$", views.ExpenseDelete.as_view(), name="expense-delete"),
    re_path(r"^expense/create/$", views.ExpenseCreate.as_view(), name="expense-create"),


    re_path(r"^subscriptions/$", views.subscriptions, name="subscription-list"),

    re_path(r"^suggestions/$", views.SuggestionCreate.as_view(), name="suggestions"),
    re_path(r"^suggestion/edit/(?P<pk>\d*)/$", views.SuggestionUpdate.as_view(), name="suggestion-edit"),
    re_path(r"^suggestion/delete/(?P<pk>\d*)/$", views.SuggestionDelete.as_view(), name="suggestion-delete"),

    re_path(r"^events/$", views.EventCreate.as_view(), name="events"),
    re_path(r"^event/(?P<pk>\d*)/$", views.EventUpdate.as_view(), name="event-edit"),
    re_path(r"^event/(?P<pk>\d*)/over/$", views.event_over, name="event-over"),
    re_path(r"^event/(?P<pk>\d*)/repeat/$", views.repeat_event, name="event-repeat"),
    re_path(r"^event/delete/(?P<pk>\d*)/$", views.EventDelete.as_view(), name="event-delete"),

    re_path(r"^todos/$", views.TodoCreate.as_view(), name="todos"),
    re_path(r"^todo/(?P<pk>\d*)/$", views.TodoUpdate.as_view(), name="todo-edit"),
    re_path(r"^todo/(?P<pk>\d*)/done/$", views.todo_done, name="todo-done"),
    re_path(r"^todo/(?P<pk>\d*)/priority_increase/$", views.todo_priority_increase, name="todo-priority-increase"),
    re_path(r"^todo/(?P<pk>\d*)/priority_decrease/$", views.todo_priority_decrease, name="todo-priority-decrease"),
    re_path(r"^todo/delete/(?P<pk>\d*)/$", views.TodoDelete.as_view(), name="todo-delete"),

    re_path(r"^media/$", views.MediaCreate.as_view(), name="media-list"),
    re_path(r"^media/(?P<pk>\d*)/$", views.MediaUpdate.as_view(), name="media-update"),
    re_path(r"^media/(?P<pk>\d*)/delete/$", views.MediaDelete.as_view(), name="media-delete"),

    re_path(r"^tasks/create/$", views.TaskCreate.as_view(), name="task-create"),
    re_path(r"^tasks/$", views.TaskListView.as_view(), name="task-list"),
    re_path(r"^tasks/(?P<pk>\d*)/done/$", views.mark_task_done, name="task-done"),
    re_path(r"^tasks/edit/(?P<pk>\d*)/$", views.TaskUpdate.as_view(), name="task-edit"),
    re_path(r"^tasks/delete/(?P<pk>\d*)/$", views.TaskDelete.as_view(), name="task-delete"),

    re_path(r"^accounts/create/$", views.MoneyAccountCreate.as_view(), name="accounts-create"),
    re_path(r"^accounts/$", views.MoneyAccountListView.as_view(), name="accounts-list"),
    re_path(r"^accounts/(?P<pk>\w*)/$", views.MoneyAccountDetailView.as_view(), name="accounts-detail"),
    re_path(r"^accounts/(?P<pk>\w*)/terminate-savings-deposit/$", views.terminate_savings_deposit, name="terminate-savings-deposit"),
    re_path(r"^accounts/(?P<account_pk>\w*)/create-savings-deposit/$", views.create_savings_deposit, name="create-savings-deposit"),

    re_path(r"^accounts/edit/(?P<pk>\w*)/$", views.MoneyAccountUpdate.as_view(), name="accounts-edit"),
    re_path(r"^accounts/delete/(?P<pk>\w*)/$", views.MoneyAccountDelete.as_view(), name="accounts-delete"),

    re_path(r"^users/$", views.UserListView.as_view(), name="user-list"),

    re_path(r"^dns_tunnel/$", views.dns_tunnel_view, name="dns-tunnel"),

    path("", include(tasks_api_router.urls)),
]


urlpatterns += [
    path("admin/", admin.site.urls),
]

urlpatterns += [
    path('api/token/', TokenObtainPairView.as_view(), name='token-obtain-pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/familytool/models.py
from datetime import datetime
from random import randint
from dateutil.relativedelta import relativedelta
from decimal import Decimal

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator

from familytool.utils import ChoiceArrayField


REPEAT_EVERY = (
    ("--", _("--")),
    ("day", _("day")),
    ("week", _("week")),
    ("two_weeks", _("two_weeks")),
    ("month", _("month")),
    ("year", _("year")),
    ("workday", _("workday")),
    ("weekend", _("Weekend")),
    ("I", _("I")),
    ("II", _("II")),
    ("III", _("III")),
    ("IV", _("IV")),
    ("V", _("V")),
    ("VI", _("VI")),
    ("VII", _("VII")),
)


class Tag(models.Model):
    title = models.CharField(_("Title"), max_length=128, null=True)
    slug = models.SlugField(_("Slug"), max_length=128)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("recipe-list")

    def __str__(self):
        return self.title or self.slug


class Recipe(models.Model):
    title = models.CharField(_("Title"), max_length=255)
    engredients = models.TextField(_("Engridients"))
    preparation = models.TextField(_("Preparation"))
    tags = models.ManyToManyField("Tag", related_name="recipes")
    url = models.URLField(max_length=1024, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("recipe-list")

    def __str__(self):
        return self.title or "Recipe object"

class Unit(models.Model):
    title = models.CharField(max_length=128)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("recipe-list")

    def __str__(self):
        return self.title


class Item(models.Model):
    title = models.CharField(max_length=128)
    comment = models.TextField(null=True, blank=True, default=None)
    amount = models.DecimalField(max_digits=5, decimal_places=3, default=1)
    price = models.DecimalField(max_digits=8, decimal_places=3, default=0)
    unit = models.ForeignKey("Unit", null=True, default=3, on_delete=models.CASCADE)
    already_bought = models.BooleanField(default=False)
    bought = models.DateTimeField(null=True, blank=True)
    expires = models.DateField(null=True, blank=True)
    priority = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("item-list")

    def __str__(self):
        return "%s, %g %s" % (self.title, self.amount, self.unit)

    def save_as_bougth(self, expires=None):
        self.already_bought = True
        self.bought = datetime.now()
        self.amount = str(self.amount)
        if expires:
            self.expires = expires
        self.save()


class Expense(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    products = models.TextField()
    category = models.CharField(max_length=128, default="maistas")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse("expense-list")

    def __str__(self):
        return "%.2f lt - %s" % (self.amount, self.products)


class Suggestion(models.Model):
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("suggestions")


class Event(models.Model):
    DURATIONS = (
        ("--", _("--")),
        ("week", _("week")),
        ("two_weeks", _("two_weeks")),
        ("month", _("month")),
        ("year", _("year")),
    )
    title = models.CharField(max_length=256, null=True, blank=True)
    date = models.DateTimeField()
    time = models.TimeField(null=True, blank=True)
    url = models.URLField(max_length=256, null=True, blank=True)
    repeat_every = models.CharField(max_length=40, choices=DURATIONS, default="--")   # icon-repeat
    over = models.BooleanField()
    comment = models.TextField(null=True, blank=True, default="")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("events")


class Todo(models.Model):
    title = models.CharField(max_length=256, null=True, blank=True)
    comment = models.TextField(null=True, blank=True, default="")

    done = models.BooleanField()

    deadline = models.DateTimeField(null=True, blank=True)
    priority = models.IntegerField(default=1)
    url = models.URLField(max_length=256, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todos")


class Media(models.Model):
    MEDIA_TYPES = (
        ("book", _("Book")),
        ("movie", _("Movie")),
    )
    title = models.CharField(max_length=256, null=True, blank=True)
    type = models.CharField(max_length=256, choices=MEDIA_TYPES, default="book")
    url = models.URLField(max_length=256, null=True, blank=True)
    got = models.BooleanField()
    comment = models.TextField(null=True, blank=True, default="")
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("media-list")


class User(AbstractUser):
    username = models.CharField(
        _('username'),
        max_length=150,
        primary_key=True,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[UnicodeUsernameValidator()],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    def __str__(self):
        return f"{self.first_name or self.username or self.email}"


TASK_TYPES = (
    ("discipline", "discipline"),
    ("feature", "feature"),
)

class Task(models.Model):
    content = models.TextField(null=True, blank=True, default="")

    finished = models.BooleanField(default=False)
    type = models.CharField(max_length=40, choices=TASK_TYPES, default="discipline")

    deadline = models.DateTimeField(null=True, blank=True)
    priority = models.IntegerField(default=1, help_text="Field used for task ordering, greater - first")

    date = models.DateTimeField(null=True, blank=True, help_text="At which time this task should be done")
    time = models.TimeField(null=True, blank=True, help_text="At which date this task should be done")

    repeat_every = models.CharField(max_length=40, choices=REPEAT_EVERY, default="--", help_text=(
        "How often this task should be done"))

    frequency = ChoiceArrayField(models.CharField(max_length=90, choices=REPEAT_EVERY), blank=True, default=list)

    points = models.IntegerField(default=1, help_text=(
        "How hard is it to make this task according to Scrum point table"))
    # When showing tasks, check task history if this criteria is met.

    url = models.URLField(max_length=256, null=True, blank=True, help_text=(
        "Some tasks required interaction with external tools, this field allows to "
        "save URL of external tools for easier access"))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse("task-edit")


class TaskDone(models.Model):
    task = models.ForeignKey(Task, null=True, on_delete=models.CASCADE, related_name="done_set")
    done_at = models.DateTimeField(auto_now_add=True)
    points = models.IntegerField(default=1, help_text="How hard is it to do this task in points?")
    user = models.ForeignKey(User, on_delete=models.CASCADE)


PRODUCT_CATEGORIES = (
    ("maistas", _("Maistas")),
)

class Product(models.Model):
    name = models.CharField(max_length=128, default="maistas")
    image = models.ImageField(upload_to="product_images")
    category = models.CharField(max_length=128, choices=PRODUCT_CATEGORIES, default="maistas")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


def generate_account_serial_number(*args, **kwargs):
    # TODO: collisions might occour if the same number is generated.
    #       Serial should be used instead.
    return f"acc{randint(1000000, 9999999)}"


class AccountLog(models.Model):
    diff = models.DecimalField(max_digits=20, decimal_places=2)
    reason = models.TextField(_("Comment"))
    account = models.ForeignKey("MoneyAccount", on_delete=models.CASCADE, related_name="logs")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]


class MoneyAccount(models.Model):
    id = models.CharField(max_length=512, default=generate_account_serial_number, primary_key=True)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=512)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def add(self, diff: float, reason: str):
        AccountLog.objects.create(account=self, diff=diff, reason=reason)
        self.amount += Decimal(diff)
        self.save(update_fields=["amount"])

    def __repr__(self):
        return f"{self.id} {self.amount} {self.name} - {self.user.username}"

    class Meta:

app/familytool/forms.py
from functools import partial
from datetime import datetime

from django import forms
from django.contrib.admin.widgets import AdminDateWidget

from familytool.models import Item, Event, Media, Todo, Task

DateInput = partial(forms.DateInput, {"class": "datepicker", "autocomplete": "off"})


class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        exclude = ["bought", "expires", "already_bought"]


class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # self.initial.update({"date": str(datetime.now().today())})

    class Meta:
        model = Event
        exclude = []
        widgets = {
            "date": DateInput(),
        }


class TodoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Todo
        exclude = []
        widgets = {
            "deadline": DateInput(),
        }


class MediaForm(forms.ModelForm):
    class Meta:
        model = Media
        exclude = []


class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Task
        exclude = []
        widgets = {"deadline": DateInput()}

app/familytool/templates/familytool/event_form.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    {% include 'menu.html' %}
{% endblock %}

{% block content %}
<a class='pull-right' href="{% url 'events' %}?all=true">visi</a>
{% for event in events %}
<p style="display: inline;">
<span style="color: {% if event.date.date < today %}#aa4400;{% else %}
    {% if event.date.date >= today and event.date.date <= tomorrow %}#999900;{% else %}#449900;{% endif %}{% endif %}">
        <b >{{ event.date|date:"Y-m-d" }}</b> {% if event.time %}{{ event.time|time:"H:i" }}{% endif %}
    </span>
    <a href='{{ event.url }}'>{{ event.title }}</a> {{ event.comment|truncatechars:170 }}
    <a href="{% url 'event-edit' event.pk %}"><button class="btn btn-small"><i class="icon-pencil"></i></button></a>
    {% if not event.repeat_every == '--' %}
        <form method="post" action="{% url 'event-repeat' event.pk %}" style="display: inline; margin: 0;">
            {% csrf_token %}
            <button class="btn btn-small" type='submit'><i class="icon-repeat"></i></button>
        </form>
    {% else %}
        <form method="post" action="{% url 'event-over' event.pk %}" style="display: inline; margin: 0;">
            {% csrf_token %}
            <button class="btn btn-small"><i class="icon-check"></i></button>
        </form>
    {% endif %}
    <!--<form action="{% url "event-delete" event.pk %}" method="post" style="display: inline;">{% csrf_token %}
        <button class="btn btn-small" action="submit"><i class="icon-remove"></i></button>
    </form>--><br/>
</p>
{% endfor %}

<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.errors }}
    {% for field in form %}
    <p> {{ field.errors }}
    {% if field.name == 'comment' %}
        {{ field.label_tag }} {{ field }}
    {% else %}
        {% if field.name == 'date' %}
            {{ field.label_tag }} {{ field }}
            {{ form.time.label_tag }} {{ form.time }}
        {% else %}
            {% if not field.name == 'time' %}
                {{ field.label_tag }} {{ field }}
            {% endif %}
        {% endif %}
    {% endif %}
    </p>
    {% endfor %}
    <input class="btn" type="submit" value="{% trans "Save" %}" />
</form>

{% endblock %}

app/familytool/templates/familytool/event_update.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    {% include 'menu.html' %}
{% endblock %}

{% block content %}
<div class="offset3 span7 inline">
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="pull-right">{{ form.instance.created|date:"Y-m-d H:i" }}</div>
    {{ form.as_p }}
    <input class="btn" type="submit" value="{% trans "Save" %}" />
</form>
<form action="{% url 'event-delete' form.instance.pk %}" method="post">{% csrf_token %}
    <input class="btn btn-small btn-inverse pull-right" type="submit" value="{% trans "Delete" %}" />
</form>
</div>
{% endblock %}

app/familytool/templates/familytool/expense_list.html
{% extends "base.html" %}
{% load i18n %}
{% load showbrs from customtemplatetags %}

{% block menu %}
    {% include 'menu.html' with active="expenses" %}
{% endblock %}


{% block content %}
{% get_current_language as lang %}

<p>
Šį mėnesį: <a>{{ month_expense }}</a> &nbsp; Maistui: <a>{{ month_food_expense }}</a> &nbsp; Iš viso: <a>{{ total_expense }}</a> 
</p>
{% for obj in object_list %}
    <li><a href="/expense/edit/{{ obj.pk }}/">{{ obj }}</a>
{% endfor %}
</ul>
{% if is_paginated %}
<div class="pagination">
    <span class="page-links">
        {% if page_obj.has_previous %}
            <a href="{% url 'expense-list' %}?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span class="page-current"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.  </span>
        {% if page_obj.has_next %}
            <a href="{% url 'expense-list' %}?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endif %} 

{% endblock %}

app/familytool/templates/familytool/item_form.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    {% include 'menu.html' %}
{% endblock %}

{% block content %}
<div class="offset2 span7 inline">
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="{% trans "Save" %}" />
</form>
<form action="{% url 'item-delete' form.instance.pk %}" method="post">{% csrf_token %}
    <input class="btn btn-small btn-inverse pull-right" type="submit" value="{% trans "Delete" %}" />
</form>
</div>
{% endblock %}

app/familytool/templates/familytool/item_list.html
{% extends "base.html" %}
{% load i18n %}
{% load showbrs from customtemplatetags %}

{% block menu %}
    {% include 'menu.html' with active="items" %}
{% endblock %}


{% block content %}
{% get_current_language as lang %}

<p>
    <a href="{% url 'item-list' %}">{% trans "Needed items" %}</a>&nbsp;&nbsp;|&nbsp;
    <a href="{% url 'bought-list' 'bought' %}">{% trans "All items" %}</a>
</p>
{% for item in object_list %}
<p style="display: inline;">
    <small>{{ item.priority }}</small>
    <a href="{% url 'item-priority-increase' item.pk %}"><i class="icon-chevron-up"></i></a>
    {% if item.price %}
    <small>{{ item.price|floatformat }}€</small>
    {% endif %}
    <a href="/item/edit/{{ item.pk }}/">{{ item }}</a>
    {% if not item.already_bought %}
        <form style="display: inline" action="/item/bought/{{ item.pk }}/" method="post">
            {% csrf_token %}
            <button class="btn btn-mini">✓</button>
        </form>
    {% else %}
    <br/>
    {% endif %}
</p>
{% endfor %}

{% endblock %}

app/familytool/templates/familytool/media_form.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    {% include 'menu.html' with active='media' %}
{% endblock %}

{% block content %}
{% for media in media_list %}
<p style="display: inline;"><b>{{ media.type }}</b> <a href='{{ media.url }}'>{{ media.title }}</a> {{ media.comment }}
    <a href="{% url 'media-update' media.pk %}"><button class="btn btn-small"><i class="icon-pencil"></i></button></a><br/>
</p>
{% endfor %}

<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="{% trans "Save" %}" />
</form>

{% endblock %}

app/familytool/templates/familytool/media_update.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    {% include 'menu.html' %}
{% endblock %}

{% block content %}
<div class="offset3 span7 inline">
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="pull-right">{{ form.instance.created|date:"Y-m-d H:i" }}</div>
    {{ form.as_p }}
    <input class="btn" type="submit" value="{% trans "Save" %}" />
</form>
<form action="{% url 'media-delete' form.instance.pk %}" method="post">{% csrf_token %}
    <input class="btn btn-small btn-inverse pull-right" type="submit" value="{% trans "Delete" %}" />
</form>
</div>
{% endblock %}

app/familytool/templates/familytool/recipe_form.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    {% include 'menu.html' with active="add_recipe" %}
{% endblock %}

{% block content %}
<div class="offset3 span7 inline">
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn" type="submit" value="{% trans "Save" %}" />
</form>
{% if form.instance.pk %}
<form action="{% url 'recipe-delete' form.instance.pk %}" method="post">{% csrf_token %}
    <input class="btn btn-small btn-inverse pull-right" type="submit" value="{% trans "Delete" %}" />
</form>
{% endif %}
</div>
{% endblock %}

app/familytool/templates/familytool/red.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    {% include 'menu.html' with active="red" %}
{% endblock %}

{% block content %}
<div class="offset3 span7 inline"></div>
<div class="offset3 span7 inline">
    <ul style="list-style-type: '\27A4&nbsp;'">

        <li><code>deadcode</code> v2 with <code>--fix</code> implementation.</li>


    </ul>
</div>
{% endblock %}

app/familytool/templates/familytool/subscriptions.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
    {% include "menu.html" with active="prenumeratos" %}
{% endblock %}


{% block content %}

<p><a href="https://speakly.me">Speakly</a> - kalbų mokymuisi (lifetime).</p> <br/>
<p><a href="https://Shuffle.dev">Shuffle.dev</a> - drag and drop tinklapių dizainui kurti (lifetime).</p> <br/>
<p><a href="https://Udemy.com">Udemy.com</a> - išpirkta daugybė skirtingų kursų (lifetime). <br/>
    <ul>
    <li>Linux</li>
    <li>AWS</li>
    <li>Google Cloud Provider</li>
    <li>VIM</li>
    <li>Public Speaking</li>
    <li>ReactJS</li>
    </ul>
</p>
<p><a href="https://www.learnvim.com">LearnVim</a> - VIM editing basics (lifetime).</p> <br/>
<p><a href="https://libgen.rs">Library Genesis</a> - el. knygų rinkinys.</p> <br/>

<p>Neaktyvūs:
<ul>
<li> <a href="https://blinkist.com">Blinkist</a> - knygų santraukų klausymui</li>
<li> <a href="#">HeadWay</a> - knygų santraukų klausymui</li>
</ul>
</p>

{% endblock %}